version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install --production
  build:
    commands:
      - aws cloudformation package --template-file sam-template.yaml --s3-bucket $S3_BUCKET --s3-prefix githubprchannels --output-template-file cloudformation/template.yaml
artifacts:
  files:
    - cloudformation/template.yaml
    - cloudformation/template-config.json
    - cloudformation/service-config.json
