AWSTemplateFormatVersion: 2010-09-09

Resources:

  ServicePipelineStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
        Fn::Join:
        - '/'
        - - Fn::ImportValue: CloudFormationTemplatesBucketURL
          - development
          - stack-set-pipeline.yaml

      Parameters:
        StackSetName: GitHubChannels
        StackSetDescription: GitHub/Slack integration that posts updates for a particular github project to slack.
        CodeRepo: slack
        # ProdAwsAccountId: '958870741793'
        BuildImage: aws/codebuild/standard:2.0
        TestImage: aws/codebuild/standard:2.0
